#!/usr/bin/python
# -*- coding: utf8 -*-
#IMPORT LIBRARY FOR MYSQL
import MySQLdb
#SETUP DATABASE INFORMATION
from DBconfig import DBHOST, DBUSER, DBPASSWORD, DBNAME

database = MySQLdb.connect(DBHOST, DBUSER, DBPASSWORD, DBNAME, charset="utf8", use_unicode=True)

cursor = database.cursor()

def create_hiragana():
    print("CREATING TABLE hiragana")
    cursor.execute("DROP TABLE IF EXISTS hiragana;")
    cursor.execute("""CREATE TABLE hiragana (
        start VARCHAR(2),
        a VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
        i VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
        u VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
        e VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
        o VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL);""")

    print("INSERTING DATA TO TABLE hiragana")
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"a", u"あ", u"い", u"う", u"え", u"お"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"k", u"か", u"き", u"く", u"け", u"こ"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"s", u"さ", u"し", u"す", u"せ", u"そ"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"t", u"た", u"ち", u"つ", u"て", u"と"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"n", u"な", u"に", u"ぬ", u"ね", u"の"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"h", u"は", u"ひ", u"ふ", u"へ", u"ほ"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"m", u"ま", u"み", u"む", u"め", u"も"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"r", u"ら", u"り", u"る", u"れ", u"ろ"))
    
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"g", u"が", u"ぎ", u"ぐ", u"げ", u"ご"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"z", u"ざ", u"じ", u"ず", u"ぜ", u"ぞ"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"d", u"だ", u"ぢ", u"づ", u"で", u"ど"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"b", u"ば", u"び", u"ぶ", u"べ", u"ぼ"))
    cursor.execute("INSERT INTO hiragana (start, a, i, u, e, o) VALUES (%s, %s, %s, %s, %s, %s)", (u"p", u"ぱ", u"ぴ", u"ぷ", u"ぺ", u"ぽ"))

    print("INSERTED DATA TO TABLE hiragana\n")
    database.commit()

def create_verb_specialform():
    print("CREATING TABLE verb_special_form")
    cursor.execute("DROP TABLE IF EXISTS verb_special_form")
    cursor.execute("""CREATE TABLE verb_special_form (
            dictionary_form VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            stem_form VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            present VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            negative VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            te_form VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past_negative VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            negative_short VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past_short VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past_negative_short VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci);""")

    print("INSERTING DATA TO TABLE verb_special_form")
    cursor.execute("INSERT INTO verb_special_form (dictionary_form, stem_form, present, negative, te_form, past, past_negative,negative_short, past_short, past_negative_short) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (u"くる", u"く", u"きます", u"きません", u"きて", u"きました", u"きませんでした",  u"こない", u"きた", u"こなかった"))
    cursor.execute("INSERT INTO verb_special_form (dictionary_form, stem_form, present, negative, te_form, past, past_negative,negative_short, past_short, past_negative_short) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (u"する", u"す", u"します", u"しません", u"して", u"しました", u"しませんでした",  u"しない", u"した", u"しなかった"))
    cursor.execute("INSERT INTO verb_special_form (dictionary_form, stem_form, present, negative, te_form, past, past_negative,negative_short, past_short, past_negative_short) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", (u"いく", u"い", u"いきます", u"いきません", u"いって", u"いきました", u"いきませんでした",  u"いかない", u"いった", u"いかなかった"))

    print("INSERTED DATA TO TABLE verb_special_form\n")
    database.commit()

def create_adjective_specialform():
    print("CREATING TABLE adjective_special_form")
    cursor.execute("DROP TABLE IF EXISTS adjective_special_form")
    cursor.execute("""CREATE TABLE adjective_special_form (
            dictionary_form VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            present VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            negative VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past_negative VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            te_form VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            negative_short VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past_short VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
            past_negative_short VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci)""")
    
    print("INSERTING DATA TO TABLE adjective_special_form")
    cursor.execute("INSERT INTO adjective_special_form (dictionary_form, present, negative, past, past_negative, te_form, negative_short, past_short, past_negative_short) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)", (u"いい", u"いいです", u"よくないです", u"よかったです", u"よくなかったです", u"よくて", u"よくない", u"よかった", u"よくなかった"))
    
    print("INESRTED DATA TO TABLE adjective_special_form\n")
    database.commit()

def create_ruverb():
    print("CREATING TABLE ru_verb")
    cursor.execute("DROP TABLE IF EXISTS ru_verb")
    cursor.execute("""CREATE TABLE ru_verb (
            verb VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL);""")

    print("INSERTING DATA TO TABLE ru_verb")
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"食べる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"たべる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"起きる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"おきる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"寝る",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"ねる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"みる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"見る",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"いる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"出かける",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"でかける",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"開ける",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"あける",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"教える",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"おしえる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"降りる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"おりる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"閉める",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"しめる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"シャワーを浴びる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"シャワーをあびる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"電話をかける",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"でんわをかける",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"忘れる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"わすれる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"かける",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"きる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"つとめる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"やせる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"じろじろみる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"すてる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"はじめる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"おぼえる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"でる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"出る",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"きめる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"つかれる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"やめる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"せきがでる",))  
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"わかれる",)) 
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"あきらめる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"あげる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"くれる",))
    cursor.execute("INSERT INTO ru_verb (verb) VALUES (%s)", (u"できる",))

    print("INSERTED DATA TO TABLE ru_verb\n")
    database.commit()

def create_verb():
    print("CREATING TABLE verb")
    cursor.execute("DROP TABLE IF EXISTS verb;")
    cursor.execute("""CREATE TABLE verb(
        word VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci,
        meaning VARCHAR(50),
        chapter INT);""")
    
    print("INSERTING DATA TO TABLE verb")
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"いく", u"to go"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"かえる", u"to return"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"きく", u"to listen"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"のむ", u"to drink"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"はなす", u"to speak"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"よむ", u"to read"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"おきる", u"to get up"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"たべる", u"to eat"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ねる", u"to sleep"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 3)", (u"みる", u"to see"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"あう", u"to meet"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ある", u"there is"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"かう", u"to buy"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"かく", u"to write"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"とる", u"to take (a picture)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"まつ", u"to wait"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"わかる", u"to understand"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 4)", (u"いる", u"(a person) is in"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 5)", (u"およぐ", u"to swim"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 5)", (u"きく", u"to ask"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 5)", (u"のる", u"to ride"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 5)", (u"やる", u"to do"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 5)", (u"でかける", u"to go out"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"あける", u"to open"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"おしえる", u"to teach"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"おりる", u"to get off"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"かりる", u"to borrow"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"しめる", u"to close"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"シャワーをあびる", u"to take a shower"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"つける", u"to turn on"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"でんわをかける", u"to make a phone call"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 6)", (u"わすれる", u"to forget"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"うたう", u"to sing"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"かぶる", u"to put on (hat)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"しる", u"to get to know"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"すむ", u"to live"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"はく", u"to put on (item below your waist)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"ふとる", u"to gain weight"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"かける", u"to put on (glasses)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"きる", u"to put on (clothes above your waist)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"つとめる", u"to work for"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 7)", (u"やせる", u"to be thin"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 8)", (u"じろじろみる", u"to stare"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 8)", (u"すてる", u"to throw away"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 8)", (u"はじめる", u"to begin"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"おどる", u"to dance"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"おわる", u"(something) ends"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"にんきがある", u"to be popular"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"はじまる", u"(something) begins"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"ひく", u"to play (string instrument or piano)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"もらう", u"to get (from somebody)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"おぼえる", u"to memorize"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 9)", (u"でる", u"to exit/ to appear"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 14)", (u"おくる", u"to send"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 14)", (u"にあう", u"to look good"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 14)", (u"あきらめる", u"to give up"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 14)", (u"あげる", u"to give"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 14)", (u"くれる", u"to give (me)"))
    cursor.execute("INSERT INTO verb (word, meaning, chapter) VALUES (%s, %s, 14)", (u"できる", u"to come into existence"))
    
    print("INSERTED DATA TO TABLE verb")
    database.commit()
 
def create_adjective():
    print("CREATE TABLE adjective")
    cursor.execute("DROP TABLE IF EXISTS adjective;")
    cursor.execute("""CREATE TABLE adjective(
            word VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
            meaning VARCHAR(50),
            chapter INT
            );""")
    
    print("INSERTING DATA TO TABLE adjective")
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 2)", (u"おいしい", u"delicious"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 3)", (u"いい", u"good"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 3)", (u"はやい", u"early"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"あたらしい", u"new"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"あつい", u"hot"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"いそがしい", u"busy"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"おおきい", u"large"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"おもしろい", u"interesting"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"かっこいい", u"good-looking"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"こわい", u"frightening"))                                                          
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"さむい", u"cold"))                                                          
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"たのしい", u"fun"))                                                          
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"ちいさい", u"small"))                                                          
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"つまらない", u"boring"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"ふるい", u"old"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"むずかしい", u"difficult"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"やさしい", u"easy/kind"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"やすい", u"cheap"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"きらいな", u"to dislike"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"きれいな", u"beautiful"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"げんきな", u"healthy/energetic"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"しずかな", u"quiet"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"すきな", u"to like"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"だいきらいな", u"to hate"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"だいすきな", u"to love"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"にぎやかな", u"lively"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 5)", (u"ひまな", u"not busy"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 6)", (u"たいへんな", u"tough(situation)"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"せがたかい", u"tall(stature)"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"せがひくい", u"short(stature)"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"ながい", u"long"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"はやい", u"fast"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"みじかい", u"short(length)"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"かわいい", u"cute"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"しんせつな", u"kind"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 7)", (u"べんりな", u"convenient")) 
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 8)", (u"じょうずな", u"good at"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 8)", (u"ひたな", u"poor at"))   
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 8)", (u"ゆうめいな", u"famous"))                                                            
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 9)", (u"あおい", u"blue"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 9)", (u"あかい", u"red"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 9)", (u"くろい", u"black"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 9)", (u"さびしい", u"lonely"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 9)", (u"しろい", u"white"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 9)", (u"わかい", u"young"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 9)", (u"いじわるな", u"mean-spirited"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 14)", (u"ほしい", u"to want"))
    cursor.execute("INSERT INTO adjective (word, meaning, chapter) VALUES (%s, %s, 14)", (u"けちな", u"stingy"))
    
    print("INSERTED DATA TO TABLE adjective")
    database.commit()

def create_katakana_vocab():
    print("CREATIGN TABLE katakana_vocab")
    cursor.execute("DROP TABLE IF EXISTS katakana_vocab")
    cursor.execute("""CREATE TABLE katakana_vocab(
            katakana VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
            meaning VARCHAR(50));""")

    print("INSERTING DATA TO TABLE katakana_vocab")
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"アメリカ", u"U.S.A."))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"イギリス", u"Britain"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"オーストラリア", u"Australia"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"スウェーデン", u"Sweden"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"アジアけんきゅう", u"Asian studies"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"コンピューター", u"computer"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ビジネス", u"business"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"メニュー", u"menu"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ジーンズ", u"jeans"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"Tシャツ", u"T-shirt"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ノート", u"note"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ペン", u"pen"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"トイレ", u"toilet"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"スポーツ", u"sport"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"デート", u"date"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"テニス", u"tennis"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"テレビ", u"TV"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"アイスクリーム", u"ice cream"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"コーヒー", u"coffee"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ハンバーガー", u"hamburger"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"アルバイト", u"part-time job"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"クラス", u"class"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"パン", u"bread"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"メール", u"e-mail"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"スーパー", u"supermarket"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"デパート", u"department store"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"バス", u"bus"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"リストラン", u"restaurant"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ホテル", u"hotel"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"サーフィン", u"surfing"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"テスト", u"test"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"シーヂィー", u"CD"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"シャワー", u"shower"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"パソコン", u"personal computer"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ページ", u"page"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"アパート", u"apartment"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ゲーム", u"game"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"コンビニ", u"convenience store"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"サークル", u"club activity"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ヂィーブイヂィー", u"DVD"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"カメラ", u"camera"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"カラオケ", u"karaoke"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"トマト", u"tomato"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ホームステイ", u"homestay"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"パーチィー", u"party"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"パーベキュー", u"barbecue"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ギター", u"guitar"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"コンサート", u"concert"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ピアノ", u"piano"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ピザ", u"pizza"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"スキー", u"ski"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"グラス", u"tumbler"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"クリスマス", u"Christmas"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"チケット", u"ticket"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"チョコレート", u"chocolate"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"トレーナー", u"sweat shirt"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ネクタイ", u"necktie"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"バレンタインデー", u"St. Valentine's Day"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ビデオカメラ", u"camcorder"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"マフラー", u"winter scarf"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"マンション", u"multistory apartment building"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ラヅオ", u"radio"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ホワイトデー", u"White Day"))
    cursor.execute("INSERT INTO katakana_vocab (katakana, meaning) VALUES (%s, %s)", (u"ワエイター", u"waiter"))

    print("INSERTED DATA TO TABLE katakana_vocab")
    database.commit()

def create_kanji():
    print("CREATING TABLE kanji")
    cursor.execute("DROP TABLE IF EXISTS kanji;")
    cursor.execute("""CREATE TABLE kanji(
            kanji VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
            hiragana VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
            meaning VARCHAR(30),
            chapter INT
            );""")

    print("INSERTING DATA TO TABLE kanji")
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"一", u"いち", u"one"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"二", u"に", u"two"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"三", u"さん", u"three"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"四", u"よん", u"four"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"五", u"ご", u"five"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"六", u"ろく", u"six"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"七", u"なな", u"seven"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"八", u"はち", u"eight"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"九", u"きゅう", u"nine"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"十", u"じゅう", u"ten"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"百", u"ひゃく", u"hundred"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"千", u"せん", u"thousand"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"万", u"まん", u"ten thousand"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"円", u"えん", u"yen"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"時", u"じ", u"time"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"百円", u"ひゃくえん", u"one hundred yen"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"一時", u"いちじ", u"one o'clock"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"一万", u"いちまん", u"ten thousand"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"十万", u"じゅうまん", u"one hundred thousand"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"百万", u"ひゃくまん", u"one million"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"三千", u"さんぜん", u"three thousand"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"八千", u"はっせん", u"eight thousand"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"千円", u"せんえん", u"one thousand yen"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"三百", u"さんびゃく", u"three hundred"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"六百", u"ろっぴゃく", u"six hundred"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 3)", (u"八百", u"はっぴゃく", u"eight hundred"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"日", u"にち", u"day"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"本", u"ほん", u"book"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"人", u"じん", u"person"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"月", u"つき", u"moon"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"火", u"ひ", u"fire"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"水", u"みず", u"water"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"木", u"き", u"tree"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"お金", u"おかね", u"money"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"土", u"つち", u"soil"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"曜", u"よう", u"weekday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"上", u"うえ", u"above"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"下", u"した", u"under"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"中", u"なか", u"inside"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"半", u"はん", u"half"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"日本", u"にほん", u"Japan"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"日曜日", u"にちようび", u"Sunday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"毎日", u"まいにち", u"every day"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"母の日", u"ははのひ", u"Mother's day"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"日記", u"にっき", u"diary"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"日本語", u"にほんご", u"Japanese language"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"日本人", u"にほんじん", u"Japanese people"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"一人で", u"ひとりで", u"alone"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"この人", u"このひと", u"this person"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"月曜日", u"げつようび", u"Monday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"一月", u"いちがつ", u"January"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"今月", u"こんげつ", u"this month"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"一か月", u"いっかげつ", u"one month"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"火曜日", u"かようび", u"Tuesday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"火山", u"かざん", u"volcano"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"花火", u"はなび", u"fireworks"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"火星", u"かせい", u"Mars"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"水曜日", u"すいようび", u"Wednesday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"水泳", u"すいえい", u"swimming"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"水道", u"すいどう", u"water supply"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"水着", u"みずぎ", u"bathing suit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"木曜日", u"もくようび", u"Thursday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"金曜日", u"きんようび", u"Friday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"料金", u"りょうきん", u"charge"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"お金持ち", u"おかねもち", u"rich person"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"土曜日", u"どようび", u"Saturday"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"土地", u"とち", u"land"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"粘土", u"ねんど", u"clay"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"曜日", u"ようび", u"day of the week"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"上手な", u"じょうずな", u"good at"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"屋上", u"おくじょう", u"rooftop"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"上る", u"のぼる", u"to go up"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"地下鉄", u"ちかてつ", u"subway"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"下手な", u"へたな", u"poor at"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"中国", u"ちゅうごく", u"China"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"中学", u"ちゅうがく", u"junior high school"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"一年中", u"いちねんじゅう", u"all year around"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"半分", u"はんぶん", u"half"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"半年", u"はんとし", u"half a year"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 4)", (u"半額", u"はんがく", u"half price"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"山", u"やま", u"mountain"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"川", u"かわ", u"river"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"元気な", u"げんきな", u"fine"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"気", u"き", u"spirit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"天", u"てん", u"heaven"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"私", u"わたし", u"I"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"今", u"いま", u"now"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"田", u"た", u"rice field"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"女の人", u"おのなのひと", u"woman"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"男の人", u"おたこのひと", u"man"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"見る", u"みる", u"to see"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"行く", u"いく", u"to go"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"食べる", u"たべる", u"to eat"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"飲む", u"のむ", u"to drink"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"山川さん", u"やまかわさん", u"Mr. Yamakawa"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"小川さん", u"おかわさん", u"Mr. Ogawa"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"元日", u"がんじつ", u"the first day of the year"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"地元", u"じもと", u"local"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"富士山", u"ふじさん", u"Mt. Fuji"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"電気", u"でんき", u"electricity"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"気持ち", u"きもち", u"feeling"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"人気", u"にんき", u"popularity"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"天国", u"てんごく", u"heaven"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"天王", u"てんのう", u"Japanese emperor"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"天才", u"てんさい", u"genius"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"今日", u"きょう", u"today"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"今晩", u"こんばん", u"tonight"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"今月", u"こんげつ", u"this month"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"今年", u"ことし", u"this year"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"田中さん", u"たなかさん", u"Mr. Tanaka"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"山田さん", u"やまださん", u"Mr. Yamada"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"田んぼ", u"たんぼ", u"rice field"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"女性", u"しょせい", u"woman"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"女の子", u"おんなのこ", u"girl"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"長女", u"ちょうじょ", u"the eldest daughter"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"男性", u"だんせい", u"man"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"男の子", u"おとこのこ", u"boy"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"男子学生", u"だんしがくせい", u"male student"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"見物", u"けんぶつ", u"sightseeing"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"花見", u"はなみ", u"flowering viewing"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"意見", u"いけん", u"opinion"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"銀行", u"ぎんこう", u"bank"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"一行目", u"いちぎょうめ", u"first line"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"旅行", u"りょこう", u"travel"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"食べ物", u"たべもの", u"food"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"食堂", u"しょくどう", u"cafeteria"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"食事", u"しょくじ", u"meal"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"朝食", u"ちょうしょく", u"breakfast"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"飲み物", u"のみもの", u"drink"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 5)", (u"飲酒運転", u"いんしゅうんてん", u"drunken driving"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"東", u"ひがし", u"east"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"西", u"にし", u"west"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"南", u"みなみ", u"south"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"北", u"きた", u"north"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"口", u"くち", u"mouth"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"出る", u"でる", u"to exit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"右", u"みぎ", u"right"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"左", u"ひだり", u"left"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"分", u"ふん", u"minute"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"先生", u"せんせい", u"teacher"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"大きい", u"おおきい", u"big"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"外", u"そと", u"outside"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"国", u"くに", u"country"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"東口", u"ひがしぐち", u"east exit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"東京", u"とうきょう", u"tokyo"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"関東", u"かんとう", u"Kanto area"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"東洋", u"とうよう", u"the East"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"西口", u"にしぐち", u"west exit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"北西", u"ほくせい", u"northwest"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"関西", u"かんさい", u"Kansai area"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"西洋", u"せいよう", u"the West"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"南口", u"みなみぐち", u"south exit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"南東", u"なんとう", u"southeast"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"南極", u"なんきょく", u"Antarctica"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"北口", u"きたぐち", u"north exit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"東北", u"とうほく", u"Tohoku area"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"北極", u"ほっきょく", u"North Pale"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 6)", (u"北海道", u"ほっかいどう", u"Hokkaido"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"彼", u"かれ", u"boyfriend"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"彼女", u"かのじょ", u"girlfriend"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"彼ら", u"かれら", u"they"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"時代", u"じだい", u"age"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"電気代", u"でんきだい", u"electricity fee"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"九十年代", u"きゅうじゅうねんだい", u"90's"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"十代", u"じゅうだい", u"in one's teens"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"代わりに", u"かわりに", u"instead"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"家族", u"かぞく", u"family"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"民族", u"みんぞく", u"race"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"水族館", u"すいぞくかん", u"aquarium"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"王族", u"おうぞく", u"member of royalty"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"留学生", u"りゅうがくせい", u"foreign students"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"留学する", u"りゅうがくする", u"to study aboard"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"留守", u"るす", u"absence from home"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"父親", u"ちちおや", u"father"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"親切な", u"しんせつな", u"kind"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"親友", u"しんゆう", u"best friend"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"両親", u"りょうしん", u"parents"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"親しい", u"したしい", u"intimate"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"母親", u"ははおや", u"mother"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"切る", u"きる", u"to cut"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"切符", u"きっぷ", u"ticket"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"切手", u"きって", u"postage stamp"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"大切な", u"たいせつな", u"precious"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"英語", u"えいご", u"English"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"英国", u"えいこく", u"England"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"英会話", u"えいかいわ", u"English conversation"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"英雄", u"えいゆう", u"hero"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"店", u"みせ", u"shop"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"店員", u"てんいん", u"store attendant"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"売店", u"ばいてん", u"stall"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"書店", u"しょてん", u"book store"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"去年", u"きょねん", u"last year"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"過去", u"かこ", u"the past"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"去る", u"さる", u"to leave"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"消去する", u"しょうきょする", u"to erase"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"急に", u"きゅうに", u"suddenly"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"急ぐ", u"いそぐ", u"to hurry"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"急行", u"きゅうこう", u"express train"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"特急", u"とっきゅう", u"super express"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"乗る", u"のる", u"to ride"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"乗り物", u"のりもの", u"vehicle"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"乗車", u"じょうしゃ", u"riding a car"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"乗馬", u"じょうば", u"horseback riding"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"本当に", u"ほんとうに", u"really"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"お弁当", u"おべんとう", u"lunch box"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"当時", u"とうじ", u"at that time"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"当たる", u"あたる", u"to hit"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"音楽", u"おんがく", u"music"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"発音", u"ほつおん", u"prnunciation"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"音", u"おと", u"sound"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"本音", u"ほんね", u"real intention"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"楽しい", u"たのしい", u"fun"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"楽器", u"がっき", u"musical instrument"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"楽な", u"らくな", u"easy"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"医者", u"いしゃ", u"doctor"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"歯医者", u"はいしゃ", u"dentist"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"医学", u"いがく", u"medical science"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"医院", u"いいん", u"clinic"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"学者", u"がくしゃ", u"scholar"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"読者", u"どくしゃ", u"reader"))
    cursor.execute("INSERT INTO kanji (kanji, hiragana, meaning, chapter) VALUES (%s, %s, %s, 14)", (u"若者", u"わかもの", u"young people"))
    
    print("INSERTED DATA TO TABLE kanji")
    database.commit()

def create_vocab():
    print("CREATING TABLE vocab")
    cursor.execute("DROP TABLE IF EXISTS vocab;")
    cursor.execute("""CREATE TABLE vocab(
            word VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
            meaning VARCHAR(50),
            chapter INT
            );""")

    print("INSERTING DATA TO TABLE vocab")
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"いま", u"now"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"えいご", u"English"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"がくせえ", u"student"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"こうこう", u"high school"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"ごご", u"P.M."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"ごぜん", u"A.M."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"さい", u"...years old"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"せんこう", u"major"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"せんせえ", u"teacher"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"だいがく", u"university"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"でんわい", u"telephone"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"ともだち", u"friend"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"なまえ", u"name"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"なに", u"what"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"にほん", u"Japan"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"はん", u"half"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"ばんごう", u"number"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"リュがくせえ", u"international student"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"わたし", u"I"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"かがく", u"science"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"けえざい", u"economics"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"こくさいかんけえ", u"international relations"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"じんるいがく", u"anthropology"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"せえじ", u"politics"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"ぶんがく", u"literature"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"れきし", u"history"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"しごと", u"job"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"いしゃ", u"doctor"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"かいしゃいん", u"office worker"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"こうこうせい", u"high school student"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"しゅふ", u"housewife"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"だいがくいんせえ", u"graduate student"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"だいがくせえ", u"college student"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"べんごし", u"lawyer"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"おかあさん", u"mother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"おとうさん", u"father"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"おねえさん", u"older sister"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"おにいさん", u"older brother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"いもうと", u"younger sister"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 1)", (u"おとうと", u"younger brother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"これ", u"this one"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"それ", u"that one"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"あれ", u"that one(over there)"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"どれ", u"which one"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"この", u"this..."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"その", u"that..."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"あの", u"that...(over there)"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"どの", u"which..."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"ここ", u"here"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"そこ", u"there"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"あそこ", u"over there"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"どこ", u"where"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"だれ", u"who"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"さかな", u"fish"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"とんかつ", u"pork cutlet"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"にく", u"meat"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"やさい", u"vegetable"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"えんぴつ", u"pencil"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"かさ", u"umbrella"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"かばん", u"bag"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"くつ", u"shoes"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"さいふ", u"wallet"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"じしょ", u"dictionary"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"じてんしゃ", u"bicycle"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"しんぶん", u"newspaper"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"とけい", u"watch/clock"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"ぼうし", u"hat"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"ほん", u"book"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"きっさてん", u"cafe"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"ぎんこう", u"bank"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"としょかん", u"libary"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"ゆうびんきょく", u"post office"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"けいざい", u"economics"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"れきし", u"history"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"おかあさん", u"mother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"おとうさん", u"father"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"いくら", u"how much"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"えん", u"yen"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"いらっしゃいませ", u"welcome (to our store)"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"おねがいします", u"...please"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"ください", u"Please give me"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"じゃあ", u"then..."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"どうぞ", u"Please"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"どうも", u"thank you"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"ちゅうごく", u"China"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 2)", (u"かんこく", u"Korea"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"えいが", u"movie"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"おんがく", u"music"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ざっし", u"magazine"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"あさごはん", u"breakfast"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"おさけ", u"sake"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"おちゃ", u"green tea"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ばんごはん", u"dinner"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ひるごはん", u"lunch"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"みず", u"water"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"いえ", u"home"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"うち", u"home"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"がっこう", u"school"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"あさ", u"morning"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"あした", u"tomorrow"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"いつ", u"when"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"きょう", u"today"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ごろ", u"at about..."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"こんばん", u"tonight"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"しゅうまつ", u"weekend"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"どようび", u"Saturday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"にちようび", u"Sunday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"まいにち", u"every day"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"まいばん", u"every night"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"あまり", u"not much"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ぜんぜん", u"not at all"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"たいてい", u"usually"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ちょっと", u"a little"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"ときどき", u"sometimes"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"よく", u"often"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"そうですね", u"that's right/let me see"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"でも", u"but"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 3)", (u"どうですか", u"how about...?"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"かいもの", u"shopping"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"あなた", u"you"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"いぬ", u"dog"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"おみやげ", u"souvenir"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"こども", u"child"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ごはん", u"rice/meal"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"しゃしん", u"picture"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"つくえ", u"desk"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"てがみ", u"letter"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ねこ", u"cat"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ひと", u"person"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"おてら", u"temple"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"こうえん", u"park"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"びょういん", u"hospital"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ほんや", u"bookstore"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"まち", u"town/city"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"きのう", u"yesterday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"じかん", u"hours"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"せんしゅう", u"last week"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"とき", u"when..."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"げつようび", u"Monday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"かようび", u"Tuesday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"すいようび", u"Wednesday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"もくようび", u"Thursday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"きにょうび", u"Friday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ぐらい", u"about"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ごめんなさい", u"I'm sorry"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"だから", u"therefore"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"かくさん", u"many"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"どうじて", u"why"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"ひとりで", u"alone"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 4)", (u"いす", u"chair"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"うみ", u"sea"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"きって", u"postal stamps"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"きっぷ", u"ticket"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"しゅくだい", u"homework"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"たべもの", u"food"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"たんじょうび", u"birthday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"てんき", u"weather"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"のみもの", u"drink"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"はがき", u"postcard"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"ひこうき", u"airplane"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"へや", u"room"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"ぼく", u"I (used by man)"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"やすみ", u"holiday"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"りょこう", u"travel"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"いっしょに", u"together"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"すごく", u"extremely"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"それから", u"and then"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"だいじょうぶ", u"it's okay"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"とても", u"very"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 5)", (u"どんな", u"what kind of"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"おかね", u"money"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"おふろ", u"bath"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"かんじ", u"Chinese character"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"きょうかしょ", u"textbook"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"こんしゅう", u"this week"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"しみんびょういん", u"municipal hospital"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"つぎ", u"next"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"でんき", u"electricity"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"でんしゃ", u"train"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"にもの", u"baggage"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"まど", u"window"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"よる", u"night"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"らいしゅう", u"next week"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"らいねん", u"next year"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"あとで", u"later on"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"おそく", u"(do something) late"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"から", u"because...."))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"けっこうです", u"That would be fine"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"すぐ", u"right away"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"ほんとうですか", u"Really?"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 6)", (u"ゆっくり", u"slowly"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"あね", u"(my) older sister"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"いもうと", u"younger sister"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"うた", u"song"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"おじいさん", u"grandfather"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"おとうと", u"younger brother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"おとこのひと", u"man"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"おにいさん", u"older brother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"おねえさん", u"older sister"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"おばあさん", u"grandmother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"おんあのひと", u"woman"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"かいしゃ", u"company"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"かぞく", u"family"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"かみ", u"hair"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"きょうだい", u"brothers and sisters"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"くち", u"mouth"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"くに", u"country"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"くるま", u"car"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"しょくどう", u"cafeteria"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"ちち", u"(my) father"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"はは", u"(my) mother"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"め", u"eye"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"めがね", u"glasses"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"なにも", u"not...anything"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"ひとり", u"one person"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"ふたり", u"two people"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"べつに", u"nothing in particular"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"もしもし", u"Hello?"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"もちろん", u"of course"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 7)", (u"よかったら", u"if you like "))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"あさって", u"the day after tomorrow"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"あめ", u"rain"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"かいしゃいん", u"office worker"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"くうき", u"air"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"けさ", u"this morning"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"こくばん", u"blackboard"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"こんげつ", u"this month"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"しごと", u"job"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"だいがくせい", u"college student"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"てんきよほう", u"weather forecast"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"ところ", u"place"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"なつ", u"summer"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"なにか", u"something"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"はし", u"chopsticks"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"ふゆ", u"winter"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"まいしゅう", u"every week"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"らいげつ", u"next month"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"いつも", u"always"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"かんぱい", u"Cheers"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"ざんえん", u"That's too bad"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"について", u"about"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"まだ", u"not...yet"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 8)", (u"みんなで", u"all together"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"いいこ", u"good child"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"いろ", u"color"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"おべんとう", u"boxed lunch"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"かぶき", u"trad. Japanese theatrical art"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"きょねん", u"last year"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"くすり", u"medicine"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"こんど", u"near future"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"さくぶん", u"essay"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"しけん", u"exam"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"せんげつ", u"last month"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"たんご", u"word/vocabulary"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"びょうき", u"illness"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"から", u"from......"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"ぜひ", u"by all mean"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"よころで", u"by the way"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"みんな", u"all"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 9)", (u"もう", u"already"))
    cursor.execute("INSERT INTO vocab (word, meaning, chapter) VALUES (%s, %s, 14)", (u"", u""))
    
    print("INSERTED DATA TO TABLE vocab")
    database.commit()



#create_hiragana()
#create_verb_specialform()
#create_adjective_specialform()
#create_ruverb()
#create_verb()
#create_vocab()
#create_adjective()
#create_katakana_vocab()
create_kanji()
